/* Three in One:
 * Describe how you could use a single array to implement three stacks.
*/

// To implement three stacks using a single array, simply d a logical partition of
// the array into three interwoven parts such taht each stack owns a set of indices.
// Stack1 owns: 3, 6, ...
// Stack2 owns: 4, 7, ...
// Stack3 owns: 5, 8, ...
// Indices 0, 1, and 2 are the "top" pointers of the stack. I.e. index 0 stores the
// index of the top of stack 1, index 2 stores the index of the top of stack 2, etc...